FROM php:8.0.16-apache

LABEL authors="Mats Löfgren <mats.lofgren@matzor.eu>, Ofek Edri <ofeked@gmail.com>"

RUN a2enmod rewrite

RUN apt-get update && apt-get install -y \
    git libfreetype6-dev libpq-dev libonig-dev libpng-dev libjpeg-dev zlib1g unzip wget && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-install mysqli mbstring && \
    docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ &&\
    docker-php-ext-install gd calendar


ENTRYPOINT ["apache2-foreground"]
