apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-q2a
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q2a
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: q2a
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mysql-config
        - secretRef:
            name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-q2a

  