apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  # sergre$#534 base64 encoded example
  MYSQL_ROOT_PASSWORD: c2VyZ3JlMA==
  # 12345678 base64 encoded example
  MYSQL_PASSWORD: MTIzNDU2Nzg=